#!/bin/sh
###############################################################################
#
# Munin plugin to monitor Zend OPCache <http://php.net/manual/en/book.opcache.php>
# By Daniel Lo Nigro <http://dan.cx/>
# Edited by Camilo Sperberg <http://unreal4u.com/>
#
# Installation:
#  1. Copy php_opcache.php file onto server and verify you can hit it in a browser
#  2. Add to Munin config:
# [php_opcache]
# env.URL http://example/php_opcache.php
###############################################################################
# Settigs required for autoconf
#%# family=auto
#%# capabilities=autoconf suggest

URL=${URL:-'http://localhost/munin_opcache.php'}

WGET=`which wget`;
WGET_FLAGS="-Yoff"; # refer to wget manual, you may set extra parameters like disable proxy
act=memory

if [ "$1" = "autoconf" ]; then
        [ -z "$URL" ] && echo "no (edit URL config in header file !)" && exit 1
        [ -n "$URL" ] && echo "yes" && exit 0
fi

if [ "$1" = "suggest" ]; then
        echo "memory"
        exit 0
fi

if [ "$1" = "config" ] && [ "$act" = "memory" ]; then

cat <<'EOM'
graph_title OPCache Restarts
graph_args -l 0 --base 1024
graph_vlabel OPCache Restarts
graph_category php
graph_order oom_restarts hash_restarts manual_restarts
graph_total Total
oom_restarts.label Out Of Memory Restarts
oom_restarts.draw STACK
oom_restarts.min 0
hash_restarts.label Hash overflow restarts
hash_restarts.draw AREA
hash_restarts.min 0
manual_restarts.label Manual calls to opcache_reset()
manual_restarts.draw AREA
manual_restarts.min 0
EOM

exit 0
fi

###############################################################################

[ -x $WGET ] && $WGET -q $WGET_FLAGS "$URL?act=$act" -O - && exit 0

exit 1

